name: "DB Deployment Pipeline"

on:
  workflow_dispatch:
    # inputs:
    #   environment:
    #     description: "Target environment"
    #     required: true
    #     default: "dev"
  push:
    branches:
      - Feature-*
      - main
      - integration
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches:
      - main
      - integration

permissions:
  id-token: write        # required for OIDC

jobs:
  # ------------------------
  # Repository Contribution Compliance Gate
  # ------------------------
  Repository-Contribution-Compliance:
    name: Repo Contribution Compliance
    uses: aba-enterprise/enterprise-ci-templates/.github/workflows/repository-contribution-compliance-template.yml@main
    with:
      base_branch: main
      jira_prefix: "SCRUM|PROJ|scrum|proj"

  # ------------------------
  # Deploy Database Changes
  # ------------------------
  deploy-database:
    name: Deploy Database Changes
    needs: Repository-Contribution-Compliance
    uses: aba-enterprise/enterprise-ci-templates/.github/workflows/liquibase-deploy-template.yml@main
    with:
      aws-region: us-east-2
      role-to-assume: arn:aws:iam::123456789012:role/GitHubActionsECSDeployRole
      secret-name: "yapp/dev/db-credentials"
      db-type: mssql
      changelog-file: db/changelog/db.changelog-master.xml
      liquibase-command: update
      contexts: "dev"
      labels: "release-2025"
      liquibase-version: "4.23.2"
      deploy-environment: "dev"

